// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDivQGnzlWqkoS1bWge-C5u6B2atw4dxkY',
//     appId: '1:1015962378878:web:2aaa6222310b4cc4fdae2f',
//     messagingSenderId: '1015962378878',
//     projectId: 'lipsumcrm',
//     authDomain: 'lipsumcrm.firebaseapp.com',
//     storageBucket: 'lipsumcrm.appspot.com',
//     measurementId: 'G-89NK01RK3H',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA_--EitfNv7KDqheMddEQy-qPHVskpRnI',
//     appId: '1:1015962378878:android:a48db6a2e107315afdae2f',
//     messagingSenderId: '1015962378878',
//     projectId: 'lipsumcrm',
//     storageBucket: 'lipsumcrm.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAZaGuhXJMa7Rbv5flb1yQVpkzr6aBQG4Q',
//     appId: '1:1015962378878:ios:e0a31759857499f6fdae2f',
//     messagingSenderId: '1015962378878',
//     projectId: 'lipsumcrm',
//     storageBucket: 'lipsumcrm.appspot.com',
//     iosBundleId: 'com.example.crmEmpApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAZaGuhXJMa7Rbv5flb1yQVpkzr6aBQG4Q',
//     appId: '1:1015962378878:ios:bee8532a1b5ff55efdae2f',
//     messagingSenderId: '1015962378878',
//     projectId: 'lipsumcrm',
//     storageBucket: 'lipsumcrm.appspot.com',
//     iosBundleId: 'com.example.crmEmpApp.RunnerTests',
//   );
// }
